database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  name: "chronosync"

app:
  host: "0.0.0.0"
  port: 8080

jwt:
  secret: "chronosync-jwt-secret-key-for-authentication-must-be-at-least-256-bits-long"
  expiration: 86400000  # 24 hours in milliseconds

flyway:
  locations: "classpath:db/migration"
